import { FileHelper, z } from '@start9labs/start-sdk'
import { sdk } from '../sdk'
import { adminUsername, configPath, dataPath } from '../utils'

const shape = z.object({
  adminPassword: z.string().nullable().catch(null),
  publicRead: z.boolean().catch(false),
})

type Config = z.infer<typeof shape>

// copyparty's config is a bespoke indented format, not YAML. The image includes
// every *.conf in /cfg alphabetically, so users can add their own beside this one.
function toFile({ adminPassword, publicRead }: Config): string {
  const accounts = adminPassword ? `  ${adminUsername}: ${adminPassword}\n` : ''
  const anonymous = publicRead ? '    r: *\n' : ''

  return `# Generated by StartOS -- edits here are overwritten.
# To add your own settings, create another .conf file in this directory.

[global]
  http-only
  e2dsa
  e2ts
  ansi
  name: copyparty
  hist: ${configPath}/hists/
  df: 4

[accounts]
${accounts}
[/]
  ${dataPath}
  accs:
    A: ${adminUsername}
${anonymous}`
}

function fromFile(raw: string): unknown {
  const password = raw.match(
    new RegExp(`^\\s*${adminUsername}:\\s*(\\S+)\\s*$`, 'm'),
  )?.[1]

  return {
    adminPassword: password ?? null,
    publicRead: /^\s*r:\s*\*\s*$/m.test(raw),
  }
}

export const copypartyConf = FileHelper.raw(
  { base: sdk.volumes.config, subpath: '00-startos.conf' },
  toFile,
  fromFile,
  (data) => shape.parse(data),
)
